# Generated by Django 5.2.1 on 2025-05-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='interes_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_MORA', 'En Mora'), ('FINALIZADO', 'Finalizado')], max_length=20),
        ),
    ]
