# Generated by Django 5.2.1 on 2025-05-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_interes_acumulado_prestamo_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='interes_acumulado',
            new_name='cuota_mensual',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_solicitud',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='plazo_meses',
            new_name='meses',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='tasa_interes',
        ),
    ]
