# Generated by Django 5.2 on 2025-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('meses_ahorro_consecutivo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('INTERES', 'Interés')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
