# Generated by Django 5.2.1 on 2025-05-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaahorro',
            name='interes_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='saldo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='ultimo_deposito',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
