# Generated by Django 5.2.1 on 2025-05-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0003_cuentaahorro_interes_acumulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoahorro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
