# Generated by Django 5.2.1 on 2025-05-31 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('VENDEDOR', 'Producto de Vendedor'), ('RESTAURANTE', 'Producto de Restaurante')], default='VENDEDOR', max_length=15),
        ),
        # La columna restaurante_id ya existe, así que omitimos esta operación
        migrations.AlterField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='vendedores.vendedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
