# Generated by Django 5.2.1 on 2025-05-31 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='producto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'RESTAURANTE'}, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
